version: '3.8'

services:
  db:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${HOST_PORT_DB}:5432"
    volumes:
     - ./initdb:/docker-entrypoint-initdb.d
    restart: always

  web:
    build: ./app
    container_name: gpsw_app
    environment:
      HOST_PORT_ORDER: ${HOST_PORT_ORDER} 
      DB_HOST: db  
      DB_PORT: 5432  
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    ports:
      - "${HOST_PORT_ORDER}:8081"
    depends_on:
      - db
    restart: always
